export {default as Navbar} from './navbar/Navbar'
export {default as Hero} from './hero/Hero'
export {default as Times} from './times/Times'
export {default as Papers} from './papers/Papers'
export {default as Footer} from './footer/Footer'
export {default as Live} from './livetv/Live'